version: "3"

services:
  backend_app:
    build:
      context: .
    container_name: backend_app
    image: backend_app
    restart: always
    entrypoint: ["/opt/app/entrypoint.sh"]
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - api_network

  tests:
    build:
      context: .
      dockerfile: "Dockerfile.tests"
    env_file:
      - .env
    depends_on:
      - backend_app
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
