version: "3"

services:
  sanatorium_app:
    build:
      context: .
    container_name: sanatorium_app
    image: sanatorium_app
    restart: always
    entrypoint: ["/opt/app/entrypoint.sh"]
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
